### ISSUE TITLE
[FEATURE] Windows installer and Package management etc. Winget / Choco

### ISSUE THREAD

**Issue by tom8zds** [sourcegit-scm/sourcegit#175]
need installer for windows or upload to package management like winget or choco, portable release not convinent when upgrade

**Comment by lgranie** [comment]
I have made a scoop manifest
[sourcegit.json](https://github.com/user-attachments/files/15884120/sourcegit.json)

**Comment by LouieTian0209** [comment]
Agreed. Having a standalone installer for Windows would be a lot better, especially since there are already deb and rpm packages for Linux.

**Comment by gadfly3173** [comment]
I tried to create a manifest for a winget package: https://github.com/gadfly3173/winget-pkgs/commit/d35d48449f92c2bcfcc756e6fa6ad6fcf49839d9 , but encountered some issues:

- Portable package installed via winget is not able to create shortcuts on the Desktop and Start Menu, while open them through the command line throws a `System.DllNotFoundException: Unable to load DLL 'libSkiaSharp' or one of its dependencies`. There is no issue when opening the application directly from the winget installation location or by using the shortcuts located in `%LOCALAPPDATA%\Microsoft\WinGet\Links`.
- winget lacks the ability to automatically detect new release versions, requiring either manually submitting a PR to the `winget-pkgs` repository or using `wingetcreate.exe` to automatically initiate the process and then manually filling out the PR content.

I think a separate installation package is helpful to improve the upgrade experience, which is also the form of installation of most GUI tools in winget.

**Comment by ZaLiTHkA** [comment]
just FYI, searching through the Scoop "apps" list page, I found a user bucket that includes Sourcegit: https://scoop.sh/#/apps?o=false&q=sourcegit

> I have made a scoop manifest [ScoopInstaller/Main#5923](https://github.com/ScoopInstaller/Main/pull/5923)

unfortunately, this PR was closed with a request to reopen it in the "Extras" bucket, but I don't think this has happened yet.

---

not to imply that a Winget package is not required, just a note to say that an installation path is currently available through Scoop.

**Comment by love-linger** [comment]
The description for this app in https://scoop.sh/#/apps?o=false&q=sourcegit is `Native Kubernetes desktop client.`.

I've created a new [package request](https://github.com/ScoopInstaller/Extras/issues/13534) to `ScoopInstaller/Extra` bucket. Hope they can add it to the offical bucket.

**Comment by ZaLiTHkA** [comment]
> The description for this app in [scoop.sh/#/apps?o=false&q=sourcegit](https://scoop.sh/#/apps?o=false&q=sourcegit) is `Native Kubernetes desktop client.`.

yeah, I did notice that, it does actually install Sourcegit though..

> I've created a new [package request](https://github.com/ScoopInstaller/Extras/issues/13534) to `ScoopInstaller/Extra` bucket. Hope they can add it to the offical bucket.

awesome.. hopefully that gets a little more visibility to this awesome Git client! :) there aren't many Linux options that come anywhere close to Sourcegit.

**Comment by tom8zds** [comment]
what about a quick and quick approach by innosetup, just pack the portable into installer

**Comment by love-linger** [comment]
> what about a quick and simple approach by innosetup, just pack the portable into installer

There is no point in providing an installer if you can't solve the problem of automatic upgrades within the installer.

**Comment by LouieTian0209** [comment]
> what about a quick and simple approach by innosetup, just pack the portable into installer

Only if it won't overwrite existing configs and histories. If innosetup installer can only overwrite/replace project files and leave configs and histories alone, then it makes sense to have it offered as an option for release.

**Comment by love-linger** [comment]
> > what about a quick and simple approach by innosetup, just pack the portable into installer
> 
> Only if it won't overwrite existing configs and histories. If innosetup installer can only overwrite/replace project files and leave configs and histories alone, then it makes sense to have it offered as an option for release.

But I can't find any advantages that compares to the portable way.

**Comment by love-linger** [comment]
https://github.com/microsoft/winget-pkgs/pull/160907

**Comment by love-linger** [comment]
![image](https://github.com/sourcegit-scm/sourcegit/assets/4075673/3460abd2-2ad8-43d2-97f3-a0fb3f92f0b4)

Now, users can install this app via
```batch
winget install SourceGit
```

Note: If you have run self-build SourceGit that based on `develop` branch after tag `v8.18`, please do NOT install from this way. It's because that after `v8.18`, the settings of repository has been moved into the repository's git dir. The `preference.json` modified by it can not be used by the older version, such as release `v8.18`

**Comment by love-linger** [comment]
It's installed SourceGit as a command-line tool. You should run it from the console or `Win+R` at the first time. Then you can add it to taskbar.

**Comment by LouieTian0209** [comment]
> > > what about a quick and simple approach by innosetup, just pack the portable into installer
> > 
> > 
> > Only if it won't overwrite existing configs and histories. If innosetup installer can only overwrite/replace project files and leave configs and histories alone, then it makes sense to have it offered as an option for release.
> 
> But I can't find any advantages that compares to the portable way.

@love-linger Sorry for the late reply. Been quite busy with life and work recently.

One advantage (albeit I agree could be a very weak argument, depending on who you ask) of having a standalone installer, is that it offers a consistent experience of getting the program ready on the system.

EXE installers are, as far as I understand, largely system agnostic and third-party dependency free. It should run exactly the same no matter which version of Windows you use, as long as it's relatively modern.

In addition, some actions that help with user experience can also be achieved using an installer, such as the ability to create a desktop shortcut as well as add a new start menu entry when installation completes, so that the user can have multiple ways to launch the program out of the box.

With portable archives, there may be discrepencies on extracting process and behavior depending on which archive software was set as default on each device, and the user needs to manually create a desktop shortcut as well as start menu entry after extraction completes.

Again, I'm fully aware that this argument could be rather weak to some people. I'm only putting it out here as my thoughts on why I personally believe having a standalone installer would in general improve the user experience by a bit.

**Comment by ZaLiTHkA** [comment]
> In addition, some actions that help with user experience can also be achieved using an installer, such as the ability to create a desktop shortcut as well as add a new start menu entry when installation completes, so that the user can have multiple ways to launch the program out of the box.

these are completely valid points, but I think we should keep in mind that "an installer" for any application is quite simply an executable program designed to extract a predetermined collection of files to a specified location, such as those built by NSIS, or Advanced Installer, etc.. how much of this process is hard-coded in the setup and how much is configurable depends entirely on the nature of the installation system in question and the options set by the person who created it.

for reference, the [Scoop manifest for SourceGit](https://github.com/ScoopInstaller/Extras/blob/master/bucket/sourcegit.json) currently downloads the relevant "portable" version and extracts it to a location that makes sense for *its own* installation process, before creating "installed program" links and Start Menu shortcuts.

> With portable archives, there may be discrepencies on extracting process and behavior depending on which archive software was set as default on each device, and the user needs to manually create a desktop shortcut as well as start menu entry after extraction completes.

I would hazard a guess and say the people who download and manually extract portable builds of any software already have their own "preferred installation process", from the archiving software they use right through to how and where they create shortcuts, if at all.

---

in my opinion, since *this* issue is technically resolved (by making SourceGit available through Winget), perhaps a separate issue could be opened for a Windows-specific executable setup package? there are numerous systems that can do this, some of which are OSS, and some of which can even be done through GitHub Actions..

this issue has already taken a few steps in the right direction for this idea, since many Windows installation package builders are simply thin wrappers around an `msi` package.
