### ISSUE TITLE
Dragging the border to resize the window looks weird

### ISSUE THREAD

**Issue by gadfly3173** [sourcegit-scm/sourcegit#177]
https://github.com/sourcegit-scm/sourcegit/assets/28685179/86674e12-fb32-4a19-9afa-1b1d1c4d5feb

It looks like dragging only works when the mouse is inside the window. When the mouse position exceeds the window, the icon becomes draggable, but the window border cannot be dragged.

**Comment by love-linger** [comment]
Commit d9e17b9 works fine on my Debian 12. Look forward to your feedback.

**Comment by gadfly3173** [comment]
Looks good on Deepin 20.9 . But Commit `762ec1f702538dd51dfb474c1197d48910352a2d` doesn't look right, the problem before I modified the BeginMoveWindow method reappeared.

**Comment by love-linger** [comment]
I can not reproduce the issue in your video on Debian 12.

https://github.com/sourcegit-scm/sourcegit/assets/4075673/99978a2b-ed9c-49b2-a356-62dd1cd41ba4

**Comment by gadfly3173** [comment]
I have only found this problem in the DDE desktop environment. I will try to fix it when I have time tomorrow.

**Comment by love-linger** [comment]
In fect, commit 762ec1f702538dd51dfb474c1197d48910352a2d is intended to solve the issue your video shows. 

With this commit, `double-click` should not trigger the `move-window` action, because it has no mouse move delta.

I'll push anthor commit to make sure that `_pressedTitleBar` is `false` while `double-click` action taking place.

**Comment by gadfly3173** [comment]
Commit [13cc494](https://github.com/sourcegit-scm/sourcegit/commit/13cc494a4882251ff4e97df3b494889309948976) seems to be working fine.
