### ISSUE TITLE
[FEATURE] Remember selected options for checkout, create branch and pull actions

### ISSUE THREAD

**Issue by EreMaijala** [sourcegit-scm/sourcegit#185]
It would be nice if SourceGit would remember the chosen way to deal with local changes if it's "Stash & Reapply" or "Do Nothing" (I almost exclusively use "Do Nothing", and it requires an extra click). "Discard" is destructive, so I would not let it remember that one.
It would also be nice if it would remember the state of "Use rebase instead of merge".

**Comment by love-linger** [comment]
My idea for these options is to **provide only the most conservative default values**, rather than keeping the most recent selection status. Because it may lead to completely different results. 

Here is an example: For the `Force push` option in the push operation, once enabled, forgetting to cancel on the next time will cause an unexpected disaster.

The same goes for `Local Changes` options. By providing secure default values, we can ensure that users do not lose data if they forget to select at least.

**Comment by EreMaijala** [comment]
@love-linger I appreciate that, but "Do nothing" isn't unsafe. It will just fail if there are local changes that prevent the operation, right?

My problem with "Stash & Reapply" is that it stages untracked files and then I have to remember to unstage them. I'd go as far as to say that it could be more unsafe than "Do nothing" since it could lead you to commit files that you were not supposed to commit. And it's not always practical to add everything to .gitignore.

**Comment by love-linger** [comment]
> @love-linger I appreciate that, but "Do nothing" isn't unsafe. It will just fail if there are local changes that prevent the operation, right?
> 
> My problem with "Stash & Reapply" is that it stages untracked files and then I have to remember to unstage them. I'd go as far as to say that it could be more unsafe than "Do nothing" since it could lead you to commit files that you were not supposed to commit. And it's not always practical to add everything to .gitignore.

I'd like to change to default action that deal with local changes to `Do Nothing`

**Comment by EreMaijala** [comment]
That'd work for me!

**Comment by love-linger** [comment]
The implementation for these two features has been pushed to branch `develop`. You can test it from this build https://github.com/sourcegit-scm/sourcegit/actions/runs/9578049402

**Comment by EreMaijala** [comment]
@love-linger Thanks, works beautifully!

**Comment by love-linger** [comment]
Since the situation I was worried about still occurred, I decided to roll back this feature.

- Applying the same operation to local change each time is not the correct way.
- Users are likely to mis-operate without noticing.
- After local unstaged and unstashed changes are wrongly deleted, there is no way to recover them. This is a very serious matter.

See #977
