### ISSUE TITLE
[FEATURE] Move, resize and change order of the columns in the history tab.

### ISSUE THREAD

**Issue by FardinHaque70** [sourcegit-scm/sourcegit#194]
Basically the title. It would be super nice to be able to resize and expand the commit user's column.

<img width="451" alt="Screenshot 2024-06-20 at 11 43 48 AM" src="https://github.com/sourcegit-scm/sourcegit/assets/44266051/7d2caa63-5634-496a-afc0-e93a782e39ed">

**Comment by love-linger** [comment]
In fact, this is intentional. The goal is to leave more space to display the subject of commit. 

For example:
![image](https://github.com/sourcegit-scm/sourcegit/assets/4075673/1f04cd75-562b-43b2-95f2-5e686a093737)

In a team, some people have very long names, while others have very short names. If width is taking from the longest, it can make space utilization very low in some cases.

![image](https://github.com/sourcegit-scm/sourcegit/assets/4075673/8c03feed-7531-4aca-b84c-e83026220539)

And as there's no header row, which will not added in near future, in the histories view, I'm going to keep it the way it is.

**Comment by love-linger** [comment]
After receiving issue about the incomplete display of the author name in the commit list multi times, I decided not to limit the maximum display width of the column
