### ISSUE TITLE
[FEATURE] Add option to prune origin branches on pull

### ISSUE THREAD

**Issue by brogan89** [sourcegit-scm/sourcegit#236]
Basically just to run `git remote update origin --prune` when you pull or fetch. 

I really like the way git Fork will also show an little icon of local branches that dont have a remote counterpark anymore. e.g when PRs are merged and branch is deleted.

**Comment by love-linger** [comment]
It's not necessary to run an extra command after pull or fetch, because there's an argument `--prune` for git `fetch` and `pull` command to do this job.

Currently, there're two way to prune remote dead branches.

* Fetch has an option to enable this argument
* You can do this from remote's context menu

I'll add an option to prune remote dead branches on pull popup.

**Comment by love-linger** [comment]
I'm sorry. Since `pull` in this app requires target remote branch, `--prune` is ignored (it does not fetch all changes from remote, but only target remote branch). I've reverted commit ab4fd081b2c3ddf78cad530e1b4be5872a15d3e8
