### ISSUE TITLE
[Feature] - Auto Update Tool

### ISSUE THREAD

**Issue by ennerperez** [sourcegit-scm/sourcegit#29]
Provide an automate way to update the application using the notification system

![image](https://github.com/sourcegit-scm/sourcegit/assets/1206858/3cb3ee96-6339-4c4e-8889-ef13ce94103f)

- [x] Update notifications models
- [x] Include action in the notification toast
- [x] Call the update tool
- [x] Recover release information from GitHub
- [x] Temporally download the release
- [x] Close and replace the existing version
- [x] Close and replace the update tool
- [ ] Cross Platform Implementation (WIP)

**Comment by love-linger** [comment]
In fact, older versions (before v6.2) of this software had a self-updating feature and it was removed for some reasons.

I would like to use a third-party library [NetSparkle](https://github.com/NetSparkleUpdater/NetSparkle) to supports self-update feature.

**Comment by love-linger** [comment]
@ennerperez If you want to implement this feature without introducing any other dependencies, I recommend not using `App.SendNotification` for notifications about updates. This is because messages sent by `App.SendNotification` will only appear on a certain page. Instead, I would like to open a new dialog window for update-available notification.

**Comment by love-linger** [comment]
After testing NetSparkleUpdater, I decided to implement a simpler one myself. 

* It will **NOT** automatically updates self but will notify user while a new version is available. Then user can go to download page by a single click.
* Checking for updates automatically on startup can be turn off by user.
* User can skip a new version.
* User can manually check for updates from main menu.
