### ISSUE TITLE
[Feature request] Action on commit double-click

### ISSUE THREAD

**Issue by julaudo** [sourcegit-scm/sourcegit#295]
If I'm not mistaken, currently double clicking on a commit does not trigger any action.

When commit is either a tag or a branch HEAD, it would seem natural to trigger a "checkout" command on this commit.

In particular, if a commit corresponds to several branches, sourcegit should detect which one has been clicked. And if none, it should ask the user to make a choice.

**Comment by julaudo** [comment]
@love-linger  I tried the feature, and I think it can be improved : when double clicking on a remote branch, if the local branch does not exist, SourceGit will checkout the commit. I think it should instead propose to create a local branch and checkout this branch.

**Comment by julaudo** [comment]
@love-linger on last thing, when double-clicking on origin/master, is local branch master exists, but has a different HEAD than origin/master, I think sourcegit should checkout the local master.

Ideally, if origin/master is more recent that master, sourcegit should checkout master an fast forward to origin/master. Maybe we could have multiple choices:
- fast forward to origin/branch
- keep existing head
- create a new branch (probably not useful if a local branch already exists)

**Comment by love-linger** [comment]
Since the software provides more than one way to switch branches:

* Double-click on the branch tree
* Using context menu from the branch tree
* Using context menu from the selected commit in histories view
​
Therefore, the behavior of double-clicking a commit in histories view is limited to the fact that it must be strongly related to the target commit. For example, in the above case, if the double-click target commit contains only the remote branch, that is, when the local branch is different from the remote branch it tracks, the software will pop up a branch creation panel based on the revision.

**Comment by love-linger** [comment]
In fact, switching branches by double-clicking a commit is more inconvenient than double-clicking the target branch in the left branch tree, because you need to find the HEAD commit of the branch first.

**Comment by love-linger** [comment]
> OK. I've been using fork for years and I have adopted certain habits, that's why I'm asking very specific request. But I can certainly change these habits!

I can understand that. I was also using Fork before. In my opinion, Fork is a really great piece of software. 

I think it was around 2019, it seems that Fork was going to charge, then I decided to write my own software, and SourceGit came along.

SourceGit references Fork in a lot of ways - but just looks like it. It's not clear how they do it, but it loads a little faster than SourceGit...
