### ISSUE TITLE
[Feature] Show commit changes when amending

### ISSUE THREAD

**Issue by julaudo** [sourcegit-scm/sourcegit#300]
In the "Changes" view, when clicking on the "Amend" checkbox, changes of the last commit should appear in the "Staged" panel.
This way, it's easy to see chunks we are going to commit. It's also an easy way to remove change from the last commit.

If there are staged changes in the working tree before clicking the button, then the staged panel should merge the changes. In this case, when unchecking, previously staged chunks should remain here (i.e. check+uncheck must be a no-op)

What I'm describing is how Fork works, and I find it very natural.

**Comment by love-linger** [comment]
See #206

**Comment by julaudo** [comment]
As mentioned in #206, it is true that we can use soft reset to the previous commit, but it's not as handy as Fork-style amend.  Moreover, we lose the last commit subject.

**Comment by love-linger** [comment]
> it is true that we can use soft reset to the previous commit, but it's not as handy as Fork-style amend.

I don't think it's more convenient to process changes by adding changes from the last commit

* It's hard to tell which ones are previous and which ones are current.
* More changes need to be checked.

Moreover, we lose the last commit subject.

* If current commit message input box is empty, after you enable the `Amend` option, the message of last commit will be filled.

**Comment by love-linger** [comment]
I've pushed a commit f55a5760135c1bd12749b4db5d8a18c7dc7d428a that implements this feature. But it causes two problems.

* Because `git stash` is used for local uncommitted changes, it may not works as expected with staged changes in `amend` mode. This issue also exists in `Fork` app.
* Since `discard` is not compatible with staged changes from HEAD commit, after commit f55a5760135c1bd12749b4db5d8a18c7dc7d428a, user can only discard unstaged changes. 

You can try it from this build https://github.com/sourcegit-scm/sourcegit/actions/runs/10173863877

**Comment by julaudo** [comment]
> You can try it from this build https://github.com/sourcegit-scm/sourcegit/actions/runs/10173863877

Seems to work perfectly!

**Comment by julaudo** [comment]
@love-linger just a small request on this. When amending, if I only modify the commit message, then sourcegit will complain because "No files added to commit!"

I understand the logic but I think this should be allowed. This is not exactly the same use case as an "empty" commit.

**Comment by love-linger** [comment]
You should use `Reword` in context menu of selected commit.
