### ISSUE TITLE
Enhancement: Double-click on origin branch of already checked-out local branch should pull from origin

### ISSUE THREAD

**Issue by warappa** [sourcegit-scm/sourcegit#337]
### Issue
Currently, if I want to update to the latest origin branch, I try to double-click the origin branch. Instead of pulling the latest commits into my already existing branch, it opens the "New Branch" modal.

#### Expected Behavior
Pull the latest changes in already checked-out local branch.

**Comment by love-linger** [comment]
1. The create branch dialog displays only when there's no local branch tracks with it. Please make sure your local branch has tracking with the target remote branch.
2. You should use `Pull` or `Fast-Forward` context menu item from local branch to update the local branch to the latest with its tracking remote branch.

If there's a local branch that tracking with the remote branch you just double-click, this app will just try to checkout this local branch without change its HEAD.

**Comment by warappa** [comment]
Yes, the 2nd option is my current workaround.

### Demo
Here's current develop's version (eb441852b0d950b2cb3417ca9a75286d6725b722) of sourcegit with the repository of sourcegit opened.

I have a local checkout of master, but I'm 43 commits behind `origin/master`.
After I double-click `origin/master`, the "Create Local Branch" dialog opens.

![image](https://github.com/user-attachments/assets/bde43a56-64e6-4a4c-ab79-805bafea22c8)

This is the current tracking configuration:
![image](https://github.com/user-attachments/assets/868c5f8a-d6e0-4b44-8185-c1795c335cef)

If I'm not missing something here, this does not work as intended.

**Comment by love-linger** [comment]
I'm sorry, I think you were talking about double-click on the branch tree……

Since the software provides more than one way to switch branches:

* Double-click on the branch tree
* Using context menu from the branch tree
* Using context menu from the selected commit in histories view
​
Therefore, the behavior of double-clicking a commit in histories view is limited to the fact that it must be strongly related to the target commit. For example, in the above case, if the double-click target commit contains only the remote branch, that is, when the local branch is different from the remote branch it tracks, the software will pop up a branch creation panel based on the revision.

**Comment by warappa** [comment]
No problem, I understand that with so many options, talking about the same is not easy. Therefore the screenshots, because "_One image says more than 1000 words_" 😉

And generally, it's good to have some options! 👍
