### ISSUE TITLE
[Feature] Git Commad line prompt

### ISSUE THREAD

**Issue by workgroupengineering** [sourcegit-scm/sourcegit#380]
Add Git command line prompt with autocomplete like this mock

![feature](https://github.com/user-attachments/assets/f4e17877-4aac-4554-868e-92c0f212d8e8)

**Comment by love-linger** [comment]
Very interesting feature. But there are serveral questions that stop me to introduce this feature into this app.

* Which git commands to be supported in the prompt? Should we introduce the document for commands?
* How do we display the output of commands since it will be very different even the same command, for example: `git log` vs `git log --pretty=format:%H`
* Since this app provides a toolbar button that supports external terminal, which will be more powerfull with auto-complete feature enabled, for example: https://www.git-scm.com/book/en/v2/Appendix-A%3A-Git-in-Other-Environments-Git-in-Zsh, I do NOT think this app will do better than that.

**Comment by workgroupengineering** [comment]
>     * Which git commands to be supported in the prompt? Should we introduce the document for commands?
> 

Initially, you may want to support all the commands in the `SourceGit.Commands` namespace, they almost all have a parser for the output. We may want to try generating the intellisese using Source Generator.

>     * How do we display the output of commands since it will be very different even for the same command, for example: `git log` vs `git log --pretty=format:%H`

as  @aikawayataro tell, we can o handle output and output history.


 
>     * Since this app provides a toolbar button that supports external terminal, which will be more powerfull with auto-complete feature enabled, for example: https://www.git-scm.com/book/en/v2/Appendix-A%3A-Git-in-Other-Environments-Git-in-Zsh, I do NOT think this app will do better than that.

I know these features and that's where I got my inspiration from. The Git prompt should not completely replicate the terminal but should allow you to use only git commands.




> I think it's better to just integrate an in-app terminal. Not sure if there's a free space where we can stick it, making GUI more complex is a bad thing by me. Implementing terminal emulator for dotnet sounds very interesting though.

I agree

**Comment by love-linger** [comment]
The original intention of this project is to provide a _**Free & Open-source & Cross-platform Git GUI Client**_. There are currently no plans to add this feature.
