### ISSUE TITLE
add a button to open the diff view in  new submodule tab view 

### ISSUE THREAD

**Issue by heartacker** [sourcegit-scm/sourcegit#385]
while the submodule is change, can we see the two commit diff in submodule tab diff-view

![image](https://github.com/user-attachments/assets/28fa7fec-1812-4169-8d4b-0907a33c4133)

**Comment by heartacker** [comment]
![image](https://github.com/user-attachments/assets/bf5a03f5-0ffc-46db-9bf5-9eb07fdcb2d4)

**Comment by love-linger** [comment]
* the parent repository of submodule only records the revision change of it
* it's hard to open submodule repository then select revisions to compare with - because there are too many jobs runs in background asynchronously
* if we show the submodule changes in the parent repository it will confuse people with paths. For example, both parent repo and submodule will have the same file `README.md`
* it needs so many refactors to support manage submodule changes in parent repository, because we need to know which repository the given paths are relative to

For the reasons list above, this feature is not planed to be added into this software.
