### ISSUE TITLE
Faulty message when trying to drag and drop git repo folder with dubious ownership

### ISSUE THREAD

**Issue by UchiTesting** [sourcegit-scm/sourcegit#397]
Good evening.
I was adding some of my repositories by drag and drop until one did not want to add up.

As the image shows this is an GIT initialised folder as the .git is present.

![image](https://github.com/user-attachments/assets/d73fa985-1636-4057-b8a6-3b1d33d8d2c5)

From CLI it gives a specific reason to that. This is because I reinstalled Windows yet the folder was already created.

![image](https://github.com/user-attachments/assets/a9d8bd6f-23e0-4ba8-a6af-b4cb6cee7520)

SourceGit should display a specific message too.

Moreover, init the folder is not a good option neither. Instead it should propose to add the folder to safe repos. Then open the repo if added to the list.

It of course works should I do what CLI output proposes.

` git config --global --add safe.directory 'D:/Users/djjax/Desktop/repos/C#/UT-EventUp-Trials'`

**Comment by love-linger** [comment]
It's because when you drop a folder, this program will try to find the real git dir (for submodules and worktrees the real git dir is not just under the repository root) via command `git rev-parse --git-dir`. Then it can open repository and setup filesystem watchers with these paths (The filesystem watchers helps us to determine what's changed and then refresh the UI).

**Comment by love-linger** [comment]
Duplicated #276

**Comment by love-linger** [comment]
I've pushed a commit to show git errors in this popup.
![image](https://github.com/user-attachments/assets/b7d9c3ba-c692-4d8e-adda-12d1842a436f)
