### ISSUE TITLE
[Feature Request] Global commit templates and issue trackers

### ISSUE THREAD

**Issue by PhilRanzato** [sourcegit-scm/sourcegit#413]
### Feature request

It would be nice to be able to set commit templates and issue trackers globally for all repositories.

In one of the latest releases it was released the ability to set commit templates (BTW that's great! I was really forward to it) and issue trackers. As far as I see this configuration can only be set at repository configuration file (`.git/sourcegit.settings`):

```json
{
  "DealWithLocalChangesOnCheckoutBranch": 1,
  ...
  "CommitTemplates": [],
  "IssueTrackerRules": []
}
```

And I don't see the same keys in the `preferences.json` file of the Application.

**Comment by love-linger** [comment]
The design of these two features refers to anthor well-known git client - `Fork`.

For `Commit Template`

* Each project will have a different commit message writing rules
* Since it's plain text, porting is also very convenient

For `Issue Trackers`

* There are several built-in rules, making it easy to set up for each repository.
* For the repository forked from anthor one, the issue tracker needs to manually point to the issues page of the original repository.
* Even if global rules are added, it is inconvenient to use only part of them

**Comment by heartacker** [comment]
great
