### ISSUE TITLE
[feature] Support selecting for font editing

### ISSUE THREAD

**Issue by successgo** [sourcegit-scm/sourcegit#450]
![image](https://github.com/user-attachments/assets/29486e45-46c0-49a8-8eee-8342103f89fd)

**Comment by love-linger** [comment]
There are two reasons that we change the font selector from ComboBox (custom font picker) to TextBox since `8.27`:

* The `FontManager.Current.SystemFonts` returns fonts with localized names, which is not supported by Skia, and currently there's no way to get the original font family name with `AvaloniaUI`. See #366 and https://github.com/AvaloniaUI/Avalonia/issues/14923#issuecomment-1994490737
* You can use composite font family names, such as `Consolas, Microsoft YaHei`, to enable font fallback when some character is missing in the first given font.

**Comment by successgo** [comment]
Good to know that, thanks.
We need to know the font name first, but it works in the hack way.
