### ISSUE TITLE
Flatpak for Linux users

### ISSUE THREAD

**Issue by lamyergeier** [sourcegit-scm/sourcegit#462]
Flatpak is supported by Gnome a major Linux Open source software developer. It provides easy package management and updating, additionally your software will feature on Gnome Software store. Appimage can't be updated but needs to be manually downloaded. And doesn't features on the Gnome software store.

**Comment by love-linger** [comment]
#93

**Comment by aikawayataro** [comment]
I've got it working with flatpak, but there are problems:

* Signing with gpg is half broken for me on X11 (host gpg-agent fails to spawn pinentry program)
* There's no proper way to spawn host terminal from flatpak. Code changes are required to workaround this

Once these things are fixed, it will be possible to submit the flatpak
I'll report and handle the first one, but the second one needs discussion, will open issue for this

**Comment by love-linger** [comment]
Thanks @aikawayataro. 

Due to some limitations of the `flatpak` mechanism, when adapting to its packaging method, some difficult-to-solve difficulties were encountered. Moreover, some changes will destroy the existing code consistency and increase the difficulty of later maintenance. 

After communicating with @aikawayataro, I decided not to go any further into this issue within the project. Of course, secondary development based on this project is completely possible (this project uses the MIT License).

**Comment by stone-w4tch3r** [comment]
Speaking about termianl issue: [host-spawn] greatly simplifies working with host terminal, and is already built-in into vscode flatpak version. May this help packaging a flatpak?

**Comment by aikawayataro** [comment]
There are also a few highlights on this topic in #479
I don't see such workarounds as a viable solution. What problem will host-spawn solve here?

**Comment by stone-w4tch3r** [comment]
@aikawayataro speaking honestly, from last messages it was not obvious what particular problems you encountered. So I mentioned host-spawn just in case 🙃
