### ISSUE TITLE
Make File browser easier to navigate

### ISSUE THREAD

**Issue by lamyergeier** [sourcegit-scm/sourcegit#463]
In the following image one needs to click precisely with mouse on black triangle to navigate down (which makes it quite time consuming), may be user could click anywhere on that row to browse under it, secondly use keyboard shortcuts like enter to navigate (currently pressing Enter does nothing)

Also, as reported in other issue there is an issue with unable to change (beyond a certain limit) column width and display of large filenames (may be users can choose to display the ending and beginning with ... in the middle for large filenames, or the files with longer filenames that don't fit the screen width, could flow from left to right as it happens on several file browser apps on Android:

![image](https://github.com/user-attachments/assets/fb214109-0fa2-4cc8-aed9-dc0820e01719)

**Comment by love-linger** [comment]
you can double click on the area that behind black triangle in the row

**Comment by lamyergeier** [comment]
Tried double clicking (look at the mouse pointer in the following image) but nothing happened:

![image](https://github.com/user-attachments/assets/36a0d2ed-c526-4dba-9ee5-192cb39a2743)

**Comment by love-linger** [comment]
As I said, you can expand/collapse a tree node by two ways:

* single-click the triangle toggle button
* double-click the area behind (not before) the triangle button

The reason why not use `Enter` key to expand/collapse tree node is that we have used it for `Stage/Unstage` operation in changes view. In order to unify the tree operation, the `Enter` key is no longer used as a shortcut for this operation.

**Comment by zaniar** [comment]
The common keyboard control for this is right arrow to expand and left arrow to collapse.

**Comment by love-linger** [comment]
> The common keyboard control for this is right arrow to expand and left arrow to collapse.

done.
