### ISSUE TITLE
[suggestion] localbranch pull suggestion

### ISSUE THREAD

**Issue by hpfs0** [sourcegit-scm/sourcegit#469]
hello
I have a very confusing problem. Every time I pull from a local branch, the wrong remote branch is pulled down. In the pull window, the remote branch is the default even if the remote branch is not tracked.
[suggestion] If the local branch does not track the remote branch, the default remote branch to be pulled is recommended to be changed to empty. thank you!

**Comment by hpfs0** [comment]
It is recommended to refer to sourcetree
![微信图片_20240913170023](https://github.com/user-attachments/assets/1b3b4fc3-6327-4904-804e-2115e4ae29bd)

**Comment by love-linger** [comment]
Since user can `Ctrl+Mouse Cllick` to run pull quickly with default parameters, the remote branch is required. Currently, if local branch does not track any remote branch, the first remote will be selected, and try to select a branch with the same name or just the first one.

The `auto-select` feature is added also because some people's feature request. See issue #342.

**Comment by love-linger** [comment]
BTW, at this point, this project has the same behavior with another well-known GIT client, `Fork`.

**Comment by hpfs0** [comment]
What I don't understand is why a local branch that doesn't track any remote branch needs to have a default remote branch to pull.
In the case of Ctrl+Mouse shortcut operation, you can just check whether there is a tracking remote branch. If there is, you can pull it. Otherwise, you are required to select it manually. Is this better? #342 issue seems does not conflict with this issue

**Comment by love-linger** [comment]
> What I don't understand is why a local branch that doesn't track any remote branch needs to have a default remote branch to pull. In the case of Ctrl+Mouse shortcut operation, you can just check whether there is a tracking remote branch. If there is, you can pull it. Otherwise, you are required to select it manually. Is this better? #342 issue seems does not conflict with this issue

Yes, you are right. Currently, I've done this job and I'm doing some testing with the modification.

**Comment by love-linger** [comment]
The new remote branch `auto-selection` algorithm will be changed to:

1. If local branch tracks some branch in selected remote, just select it.
2. If local branch tracks no branch in selected remote, but a branch with same name exists in the selected remote, select it.
3. Otherwise, leave the selected branch to empty

**Comment by hpfs0** [comment]
> The new remote branch `auto-selection` algorithm will be changed to:
> 
> 1. If local branch tracks some branch in selected remote, just select it.
> 2. If local branch tracks no branch in selected remote, but a branch with same name exists in the selected remote, select it.
> 3. Otherwise, leave the selected branch to empty

That's great. Thank you!

**Comment by love-linger** [comment]
You can test the latest build from https://github.com/sourcegit-scm/sourcegit/actions/runs/10846657299

**Comment by hpfs0** [comment]
I just test it. No problem ! Thank you !
![image](https://github.com/user-attachments/assets/0fb4a4c0-7d72-4a09-b416-3f3fc00f1cc7)
