### ISSUE TITLE
Configuration to fetch origin at launch

### ISSUE THREAD

**Issue by ghiboz** [sourcegit-scm/sourcegit#484]
should be good have a setting _(like the autofetch interval)_ to make a fetch at the startup of the ap

**Comment by love-linger** [comment]
Currently, it can be done by simply modify one line:
```diff
diff --git a/src/Models/AutoFetchManager.cs b/src/Models/AutoFetchManager.cs
index 313f5f64..2e1fb78c 100644
--- a/src/Models/AutoFetchManager.cs
+++ b/src/Models/AutoFetchManager.cs
@@ -97,7 +97,7 @@ namespace SourceGit.Models
             {
                 IndexLockFile = Path.Combine(gitDir, "index.lock"),
                 Cmd = new Commands.Fetch(repo, "--all", true, false, null) { RaiseError = false },
-                NextRunTimepoint = DateTime.Now.AddMinutes(Convert.ToDouble(Interval)),
+                NextRunTimepoint = DateTime.Now,
             };

             lock (_lock)
```
> It removes the delay for the first time running background auto-fetching.

But I'm not sure it is the right way since there's not UI/UX notification that shows a background auto-fetching task is running and the progress of that task is also invisible.

**Comment by joesponde** [comment]
When auto-fetch activates regularly in the background with current version, there is no UI/UX notification, as far as I observed.
So, it should not be "bad" to do it at launch time.
If running the autofetch directly at launch time may seem risky or a source of startup slowness. It may be delayed with a couple or a few dozens of seconds?

**Comment by love-linger** [comment]
> When auto-fetch activates regularly in the background with current version, there is no UI/UX notification, as far as I observed.

Yes, but it is very important to let users known that there's already a background fetching task running to avoid user doing it manually. For example, I'm a game developer, and after I opened the `UnrealEngine` repo, it takes a very long time before the first auto-fetching really completed. The key point is that I don't know if it has been completed or if I can do other jobs.

**Comment by love-linger** [comment]
Actually, I never use the `Auto Fetch Remote` feature...

**Comment by ghiboz** [comment]
> > When auto-fetch activates regularly in the background with current version, there is no UI/UX notification, as far as I observed.
> 
> Yes, but it is very important to let users known that there's already a background fetching task running to avoid user doing it manually. For example, I'm a game developer, and after I opened the `UnrealEngine` repo, it takes a very long time before the first auto-fetching really completed. The key point is that I don't know if it has been completed or if I can do other jobs.

I think the better way is to expose a flag in the preferences

**Comment by joesponde** [comment]
> Yes, but it is very important to let users known that there's already a background fetching task running to avoid user doing it manually. For example, I'm a game developer, and after I opened the `UnrealEngine` repo, it takes a very long time before the first auto-fetching really completed. The key point is that I don't know if it has been completed or if I can do other jobs.

I see, in this use case, auto fetch may be more complex to deal with. If I correctly understand, this use case happens when repositories are very large and very active, like with companies using mono repos (every applications, tools, libraries are stored in the same and unique repository).

For instance, in my case, I work with moderately active repositories, auto-fetch is a more than "nice to have" feature, its a highly appreciated feature.

To come back to the problematic use case, we may imagine that the first auto-fetch would start at launch time, and if the user manually clicks on the fetch button whereas auto-fetch is still going on:
- either a popup warning message opens and nothing is done,
- or the fetch subpanel is displayed (even in the case of Ctrl + Click) and the OK button remains disabled as long as the background fetch is going on, with a message in the subpanel indicating that there is a fetch in progress.

**Comment by love-linger** [comment]
I do NOT like the `Auto Fetch Remote` feature...

For large repositories, auto fetching changes from remote after repository is opened will lead to a bad experience, since git will prevent other operations that will modify the index if `index.lock` file exists. And as I said, in current implementation of auto fetching, we do NOT known if the background fetching task is completed, and also can NOT stop it to do some other emergency jobs.

Unless there is a good UI/UX design, I'll not consider to add this feature.

**Comment by love-linger** [comment]
I've rewrite the auto-fetching feature. Now it will start with 5s after a repository is opened. And a floating panel is opened to notify user there's a background fetching task is running.

**Comment by ghiboz** [comment]
> I've rewrite the auto-fetching feature. Now it will start with 5s after a repository is opened. And a floating panel is opened to notify user there's a background fetching task is running.

great! but it's been on dev branch?

**Comment by love-linger** [comment]
no, it's already available in 8.32, but the auto-fetch configuration has been moved to repository's settings not the global preference

**Comment by ghiboz** [comment]
> no, it's already available in 8.32, but the auto-fetch configuration has been moved to repository's settings not the global preference
thanks, but where I can find it? the `develop` branch is 8.29

**Comment by love-linger** [comment]
perhaps your forked repo is outdated

**Comment by ghiboz** [comment]
> perhaps your forked repo is outdated

that's my last commit:

![image](https://github.com/user-attachments/assets/96eb9d2d-5528-466a-9563-fbd242fa4caf)

**Comment by love-linger** [comment]
New settings are here.
<img width="712" alt="image" src="https://github.com/user-attachments/assets/c2ec4c5d-9c45-4d66-aee9-73fb84d21dc2">
