### ISSUE TITLE
Full statistics

### ISSUE THREAD

**Issue by Gama11** [sourcegit-scm/sourcegit#493]
Currently the statistics window is capped at one year which is not very long. How about a fourth tab showing the full statistics over the repo's lifetime?

**Comment by love-linger** [comment]
I'm very sorry, this feature will not be added to the development plan. Because the number of commits in the whole life cycle of some repository is very large, it is very time-consuming to count, and the memory consumption will also be very large. For example, the `EpicGames/UnrealEngine` repository, which I commonly use, has a total of 600K+ commits.

**Comment by Gama11** [comment]
Hm, I'd imagine that's an exception though, most people are not working with repos that large.

Maybe it could it be capped to a certain "reasonable" amount of commits? The repo I'm working on most frequently has a bit over 14k commits right now, I'd imagine that would still be pretty fast.

The problem is that the one year cap is not that useful for small-ish repos that have existed over a long time period (imagine 1000 commits over 10 years for instance).

**Comment by love-linger** [comment]
done. currently the `YEAR` tab has been replaced by `OVERVIEW` tab, which will analyze most recent 20K commits.

![image](https://github.com/user-attachments/assets/c1b159e0-3c21-42f3-8825-6243e92e159d)

You can test it from the latest build https://github.com/sourcegit-scm/sourcegit/actions/runs/10995635435

**Comment by Gama11** [comment]
Very nice, thank you. :tada:
