### ISSUE TITLE
[Feature] Configurable location for `sourcegit.settings` file

### ISSUE THREAD

**Issue by codarch** [sourcegit-scm/sourcegit#542]
It would be great if the application was able to store repository-specific configuration settings outside of the repository (the `.git` folder) and keep the repository itself clean from product-specific files. Git clients tend to treat the repository as if it were their own territory and put their arbitrary data there. That data have nothing to do with core Git files and (in my opinion) do not really belong there.

Not to mention that this practice might cause issues on a long-term period if the format of the client configuration changes (I expect future Git versions to have backward compatible changes only, but Git clients may change at a faster pace, more dynamically).

Therefore I suggest introducing an option to store repository-specific settings in a centralized manner, for instance in the _SourceGit_ application data directory.

Nonetheless this is a great product, thanks for the efforts of all contributors!

**Comment by love-linger** [comment]
* The original intention of the `.git` directory is to store repository-related configurations, current states and datas, and the `git` process does not care about files that it did not create or need.
* As far as I know, currently many tools store their own repository-related configurations and datas in the `.git` directory, including but not limited to:
  - `git-lfs` stores its blob data in the `.git/lfs-objects` directory.
  - The well-known GIT client `SourceTree` stores settings for individual repositories in the `.git/sourcetreeconfig.json` file.
  - Another well-known GIT client (which I also liked before) `fork` also stores repository-related configurations and datas in this directory.
  - The well-known 3D engine `Unreal Engine` has implemented their own large file management tool - `GitDependencies` which also stores its own data in the `.git/ue-depends` directory.
* Storing in this directory has some advantages, including but not limited to:
  - Easier to locate the configuration file.
  - When the local repository does not exist, such as when it is deleted, its configuration data is naturally deleted and no additional detection and management is needed.
  - The configuration data is not affected by the local working copy and will not be accidentally deleted due to git operations.

**Comment by codarch** [comment]
Thank you for the detailed response. You are right regarding the advantages and the list of other tools following the same practice.

I also agree with the statement that _the intention of the `.git` directory is to store repository-related configurations_, I do think however that these are not repository-related configurations, rather application-specific configurations.

The `git` process does not care about these files. I was thinking of the clients when I expressed my concerns about structural changes in configuration files. I can imagine a scenario in which a future version of a client would fail to open a repository for which it saved its configuration before, due to parsing errors in the older version of the configuration file. Migrating these configurations (in case that would ever be necessary) is nearly impossible due to the distributed nature of the current solution. (The application might keep track of repositories opened since install, but what about repositories opened before that?)

The suggestion of having an option for changing the configuration file location was made with the enumerated advantages in mind. That way the users could decide what they prefer. I understand though that from your perspective this might not worth the effort and the additional complexity, so please feel free to close this ticket. Another, simplified option to consider is to simply allow disabling repository-specific configuration storage.

**Comment by love-linger** [comment]
As this file contains data only related to the repository it is located (not like the global preference.json), it means nothing out of this repository. This program will not **detect/read/save/manage(extra operations)** this file unless the repository is opening or closing:

* on opening
  - if the `.git/sourcegit.settings` does not exists, just create a default repository settings
  - if the `.git/sourcegit.settings` exists, try to load and deserialize its content
    - if success, use it for this repository
    - otherwise, creates a new default repository settings.
* on closing
  - serialize current repository setting into the `.git/sourcegit.settings` file

Also, in the future development, I will try my best to ensure the backward compatibility for this file. New fields will have default values, and old fields will not be read. If the type of a field will be changed, a new field name will be used to discard the old values.
