### ISSUE TITLE
[ENHANCEMENT] - Files tab accessibility

### ISSUE THREAD

**Issue by Shimoon** [sourcegit-scm/sourcegit#561]
# Problem
The *Files* tab is not accessible if no commit have been selected even though this tab is not directly related to the commits themself.
Moreover, when nothing is selected, there is a lot of empty space that doesn't communicate much.
![sourcegit_file_tab_noselection](https://github.com/user-attachments/assets/d80bf56e-45d9-44e5-8d60-d6f706b41f8b)

# Proposal(s)
*(**1** or **2**, or both since I think they still make sense when combined but it should be splitted in two separate tickets in this case)*

1. Always select the **HEAD** commit by default.
    Since it doesn't really make sense to not have anything selected anyway (and because unselecting a commit is no possible either), it could be a good workaround.
2. Dissociate the *Files* tab from the commit selection.
    By either :
    - Display only the *Files* tab when nothing is selected.
    - Change the *Files* tab from its actual position to the left panel, right under the already existing *Histories*, *Changes* and *Stashes* menus. It could make more room to display the file tree and the actual files content right away.

# Mockups
*Display only the Files tab when nothing is selected :*
![sourcegit_file_tab_only](https://github.com/user-attachments/assets/ab9a8218-a4e6-4621-b6d3-305a424a890c)

*Change the Files tab from its actual position to the left panel :*
![sourcegit_file_tab_fileonleftnonselected](https://github.com/user-attachments/assets/19e54151-ac7d-4db7-b4bf-91397f8fd5fd)
![sourcegit_file_tab_fileonleftselected](https://github.com/user-attachments/assets/f47b531c-3605-4ad3-9c2d-8e978299b894)

**Comment by love-linger** [comment]
* In fact, the list of files displayed on the `FILE` page is depends on the selected commit - it shows all the files those contained in the selected revision.
* Adding a `Files` page to display the list of files in the current worktree is very limited
  - For the changed files, there is already a "Changes" page to manage them
  - For the entire worktree files, if only the content of the selected file is displayed, why not open and manage it directly with an external editor (which is more powerful)?
  - For normal operations of file-system, why not use the `Open in File Browser` feature directly?
* As mentioned in some previous issues, the left content display area is very crowded (sometimes even the `LOCAL BRANCHES` and `REMOTES` cannot be displayed completely in the same time), and there are currently no plans to add other display content
* For suggestions for automatically selecting `HEAD`, please refer to the answer in #262

**Comment by Shimoon** [comment]
> * In fact, the list of files displayed on the `FILE` page is depends on the selected commit - it shows all the files those contained in the selected revision.

I didn't thought about that, that's indeed quite logical putting it like that. Thanks for the clarification !

>     * For suggestions for automatically selecting `HEAD`, please refer to the answer in [[FEATURE REQUEST] When a worktree is opened, auto locate the HEAD #262](https://github.com/sourcegit-scm/sourcegit/issues/262)

I don't know chinese so maybe I've miss read what have been said but I don't think that this is anything close to "trying to guess the user mind" to auto focus the logical thing to view in a Git GUI client.
Currently, the empty state (nothing selected) is accessible only once, when you open a repository. As soon as you have something selected, you cannot go back to this state, which is not really intuitive in a UX perspective > if you have a state at some point, this state should be accessible again at anytime *(commit selected <-> commit unselected)*.
In my opinion, either a commit could be unseselected but there is currently no good reason to do so, or, there should always be something selected (**HEAD** by default for example).

All of this to say, I don't quite see the current logic of having nothing selected by default and so having to manually focus something when the most obvious behavior should be to view where your repository is looking at right now.
I understand the fact that this behavior may not suit some users but since this is a recurring request there should be, at least, an option to auto focus by default !

**Comment by love-linger** [comment]
* For most personal projects, after opening the repository, switching to the `changes` page to edit local changes is more frequent than checking the current HEAD. Because in most cases, we don't need to pay attention to what we committed last time.
* Even for a multi-person collaborative project, after opening the repository, if we do not fetch the changes from remote first, why should we pay attention to the HEAD that has not changed? For example, for a repository that has not been updated, why should we select the HEAD first every time we open it?
* Why not add the automatically selection? Because this action will create additional `git` processes to obtain the information we need, such as: completed commit messages (subject & body), all the changes contained in the commit, and the list of files contained in the current revision, etc. These operations will either slow down the opening time of the entire repository, or on some poorly configured computers, there will be too many git processes and they will get stuck.
* In addition, this software already provides a number of functions for quickly locating the current `HEAD`, and it is not difficult to locate the current HEAD if necessary.

**Comment by love-linger** [comment]
tips: you can hold ctrl to select multiple commits or unselect some commits

**Comment by love-linger** [comment]
> I guess that trying to fetch all the informations right at repository opening is quite like "trying to guess the user mind" actually.

Yes, you are right. So we do NOT add this feature. What I'm trying to say is that, since we do NOT know the behaviour after users open a repository, and auto-selection of `HEAD` right at repository opening will introduce additional overhead, this behavior will not be added.

> I didn't know about the CTRL key tips, that's a great one, thanks a lot!

I'll try to add some tips to help users notice this.

**Comment by love-linger** [comment]
Now the blank page has a concrete meaning: it prompts that the commits list can be multiple-selected.
![image](https://github.com/user-attachments/assets/51990aa2-dad5-454f-af21-56f803bd2d18)

**Comment by Shimoon** [comment]
Fair enough, thanks for making it clearer !
