### ISSUE TITLE
[Enhancement] Optimize fetch `prune` behavior

### ISSUE THREAD

**Issue by gadfly3173** [sourcegit-scm/sourcegit#590]
Current behavior of Fetch operation:
- Fetch popup: Follow the prune settings in the popup
- Auto Fetch: force prune
- Add Remote popup: force prune
- Pull popup: **NEVER** prune

After I delete a branch at remote, Pull will never remove the deleted remote branch. I need to click Fetch popup or wait for AutoFetch again.
I suggest to unify the prune settings and behavior in SourceGit.

**Comment by love-linger** [comment]
There are two ways to do this:

1. Removes all `--prune` parameter from `git fetch` command. And users can only do this job from the context menu of `remote`:
![image](https://github.com/user-attachments/assets/645ea31b-cc61-4727-9b5b-9bc6ddd0e003)

2. Unify all fetch-related features:
* `Fetch` will keep current design
* `Auto-Fetch` should not using `--prune` because it is not controlled by user. For example, if a remote branch is deleted by accident, we can still re-push it from our local repository.
* `Add Remote` should not using `--prune` since it is a new remote
* Add a toggle to `Push` popup that controls whether the `--prune` parameter is enabled 

Currently, I prefer the first solution

**Comment by love-linger** [comment]
Done.

**Comment by Gama11** [comment]
Hm, I'm not a fan of needing to perform one additional manual action every time I want to get rid of old merged pull request branches. :/

**Comment by gadfly3173** [comment]
> Hm, I'm not a fan of needing to perform one additional manual action every time I want to get rid of old merged pull request branches.

You can do that through git itself.

- Always auto prune: (add `--global` if you want every repository has it)
```bash
git config fetch.prune true
```

- Only prune remote with name `origin`:
```bash
git config remote.origin.prune true
```

**Comment by Gama11** [comment]
Thanks, that's good to know! :+1:

**Comment by gadfly3173** [comment]
How about adding this configuration to the preferences, or adding an option just for SourceGit? @love-linger 

Here are some other tools that handle this functionality.

GitKraken (default enabled) :
![image](https://github.com/user-attachments/assets/52c1cb3a-bbea-4644-b915-f9a9de836915)

https://github.com/mhutchie/vscode-git-graph (default disabled) :
![image](https://github.com/user-attachments/assets/e665ead3-52e0-4fc5-85bf-216d41ea557f)

https://github.com/zielu/GitToolBox (default enabled with delay) :
![image](https://github.com/user-attachments/assets/6890a0c1-d9bf-407e-8cf4-c65b5af43ac3)

**Comment by love-linger** [comment]
Done. You can download the latest CI build from Github Action.

![image](https://github.com/user-attachments/assets/6656157b-25ba-4489-b854-1aa2d7d2a193)
