### ISSUE TITLE
Add a "FETCH" option to the local branch context menu 

### ISSUE THREAD

**Issue by dougcunha** [sourcegit-scm/sourcegit#617]
Adding a "FETCH" option to the branch context menu would greatly enhance the user experience. Currently, when switching to a local branch different from the one in checkout, there's no option to synchronize with the remote. While the repository's FETCH command exists, it doesn't achieve this synchronization. 

My suggestion is to include a "FETCH" command within the local repository's context menu. This would execute the FETCH command, effectively syncing the local branch with its remote counterpart. For example, if you're on the "develop" branch and notice two commits on the "master" branch, clicking on "master" and selecting "FETCH" would execute the following command, downloading the two commits and applying them to the "master" branch:

```
git fetch origin master:master
```

**Comment by dougcunha** [comment]
I've just submitted a pull request for this: #618

**Comment by love-linger** [comment]
I've pushed my implementation of this feature. Compared to PR #618, there are the following differences:

* Add a new constructor of `Commands.Fetch`, which means it has no impact on existing `Fetch` calls (we don't need to modify existing `Fetch` calls).
* `Fetch {REMOTE_BRANCH} into {LOCAL_BRANCH}` will only be available when:
  - The selected local branch is not current branch, since we can use `Pull {REMOTE_BRANCH}` for current branch instead.
  - The selected local branch has an upstream.
  - The selected local branch is not a check-outed worktree, since `git fetch` modifies the `index` but does not update the worktree files - this operation will introduce a large number of staged changes on that worktree.
  - The selected local branch should not has ahead commits.
