### ISSUE TITLE
[Suggestion] Enhance Update Check to Include Nightly Build Versions

### ISSUE THREAD

**Issue by dougcunha** [sourcegit-scm/sourcegit#631]
Currently, when the application starts, it checks for new stable versions and notifies the user if an update is available. This improvement request proposes adding an additional configuration to check for the availability of nightly build versions during the update process.

Why?

The goal is to simplify testing of development versions before they are released. 

Requirements:

- Add a configuration setting that enables the user to choose whether the update check should look for nightly builds.
- If enabled, the application should check only for nightly versions and notify the user accordingly.
- Add a button to open the Github page with the nightly build version.
- Desirable: if running a nightly build version, a button that opens the Github to create a new issue related to the version being tested.

**Comment by love-linger** [comment]
In fact, there is no Nightly Build version of the project.

* If you're referring to the current output of Github Action, there is no need to make it a `Nightly Build` due to the large number of commits per day
* At the same time, a new version of the project is released every Monday. At this frequency, I don't think it's necessary to create a `Nightly Build` pipeline

**Comment by dougcunha** [comment]
OK. That makes sense for me. You can close this if you want.
