### ISSUE TITLE
[Commit Files Tab] Add a files search bar

### ISSUE THREAD

**Issue by albertodlc** [sourcegit-scm/sourcegit#730]
![image](https://github.com/user-attachments/assets/3356d9e1-78d6-492a-ac7a-550dcdda45d4)

**Comment by love-linger** [comment]
The revision file system tree in the `FILE` page is not calculated once. 

Instead, the first layer is calculated when the current preview commit/revision changes. And when the user expands a folder node for the first time, the next layer is calculated.

The advantages of this approach are:

* It is very fast to loading data when user changes the preview commit, basically avoids the UI lag
* Uses less memory since we just load the data we wanted
* Avoid system gc for very large repositories

For example: the `UnrealEngine` repository has 183K+ files. If we load all datas, and build the entire filesystem tree for it:

* It will take very long time to build this tree.
* It will cost very large memory to hold the datas.
* The system gc may be triggered very frequently.

So, we can not search on this tree because we do not have enough data to do this job.

**Comment by love-linger** [comment]
One more thing, I think search commit by file path is another way to do this. 
![image](https://github.com/user-attachments/assets/353bc432-5d63-4aa9-98e5-8779991e013c)
