### ISSUE TITLE
Check for updates returns 403

### ISSUE THREAD

**Issue by nsartor** [sourcegit-scm/sourcegit#75]
Hello, thanks for writing such a great tool, it's very helpful!

I was on v8.7 on Linux and wasn't able to update via the "Check for Updates" menu option. I manually updated and tried it again to see if it was something in v8.7 but I still see the error below.

There's nothing in my `~/.config/SourceGit/*.log` that's relevent.

![image](https://github.com/sourcegit-scm/sourcegit/assets/6578903/6b713b88-5e33-449c-9e05-5b4494886136)

Thank you

**Comment by love-linger** [comment]
Thank you very much for your feedback. I have changed the address to get the latest version information from `api.github.com` to `sourcegit-scm.github.io`. You can try using [this version](https://github.com/sourcegit-scm/sourcegit/actions/runs/8698509873) from Github Actions to test if this issue is resolved.

**Comment by nsartor** [comment]
Confirmed on Linux using [37ca149](https://github.com/sourcegit-scm/sourcegit/commit/37ca14997076af9cd8377ff4c690d0a98b9b10ca)
![image](https://github.com/sourcegit-scm/sourcegit/assets/6578903/74dc3392-c037-446c-a464-3895b9c7157f)

Thank you!
