### ISSUE TITLE
[Enhancement] - Use semantic version

### ISSUE THREAD

**Issue by ennerperez** [sourcegit-scm/sourcegit#79]
More information at [https://semver.org/](https://semver.org/)

**Comment by love-linger** [comment]
I don't think there's **anything wrong** with the current version number rules. You may also notice that more and more projects are customizing version number rules to suit their needs, rather than making the rules defined in https://semver.org/ the only option.

For this software, if no major refactorings are committed, the major version number is fixed at `8`. The sub-version number is an ascending sequence.

**Comment by ennerperez** [comment]
Yes, but the reason to use something like semver is a way to control the release target, at leats 3 digits are good to explains the software state:

Given a version number MAJOR.MINOR.PATCH, increment the:

MAJOR version when you make incompatible API changes
MINOR version when you add functionality in a backward compatible manner
PATCH version when you make backward compatible bug fixes

for example v8.8 means new functionalities was added since v8.7, but if we make some bug fixes without adding new features its not clear enought if that is the case.

but with 3 digits it's more clear

v.8.8.0 = new feature introduced
v8.8.1 = bug fixes
v8.8.2 = bug fixes
v8.9.0 = new feature introduced

**Comment by love-linger** [comment]
A version number with a `patch` field, usually used for software that has a long-term supported version. For this software, the version iteration is relatively frequent. The branch model is also relatively simple, with no release branches reserved for previous versions (that is, no parallel release development and maintenance schedule).
