### ISSUE TITLE
[Feature] Remember the state of checkboxes when pushing/pulling/fetching

### ISSUE THREAD

**Issue by Autre31415** [sourcegit-scm/sourcegit#824]

**Comment by love-linger** [comment]
We only remember some of those checkboxes for security reasons.

Currenly we store these options:

* `Fetch without tags` in `Fetch` and `Pull`
* `Local Changes` in `Pull`
* `Fetch all branches` in `Pull`
* `Use rebase instead of merge` in `Pull`
* `Make sure submodules have been pushed` in `Push`
* `Push all tags` in `Push`
* `Include untracked files` in `Stash Local Changes`
* `Only staged changes` in `Stash Local Changes`
* `Keep staged files` in `Stash Local Changes`

**Comment by love-linger** [comment]
Added - `--force` check state in `Fetch`
