### ISSUE TITLE
[FEATURE] - Pack in flatpak for linux

### ISSUE THREAD

**Issue by ennerperez** [sourcegit-scm/sourcegit#93]
Generate a flatpack package for linux

https://docs.flatpak.org/en/latest/first-build.html

**Comment by FardinHaque70** [comment]
I vouch for this as well! 
Getting SourceGit working on my immutable linux distro was a pain for a linux newbie like me. Please make this happen 🙏

**Comment by love-linger** [comment]
An AppImage format package has now been added for Linux

**Comment by flexxxxer** [comment]
> An AppImage format package has now been added for Linux

While AppImage is great, Flatpak provides much more then just delivering apps without headache. And AppImage not compatible with Secureblue or any other distro which [removes fuse2 due to adding attack surface](https://secureblue.dev/faq#appimage). Flatpak can run without using SUID or root privileges, provides somewhat good sandbox in case if you close known holes, like Secureblue does. 

Thanks to @MicrogamerCz and his [efforts](https://github.com/MicrogamerCz/flathub/tree/sourcegit-submission) and somewhat burned time from my side SourceGit actually runs on my machine in Flatpak few hours :) What left is to figure out how to make pgp signing working and submit an app. The way my manifest made much more better then @MicrogamerCz had done (but still thanks to him for his work!) and currently no warnings/errors for app manifest and built app repo:
```bash
flxr@venus$ flatpak run --command=flatpak-builder-lint org.flatpak.Builder manifest io.github.sourcegit_scm.sourcegit.yaml
flxr@venus$ flatpak run --command=flatpak-builder-lint org.flatpak.Builder repo repo
```

I expect to be ready for submission at the end of this week while app running in flatpak will be tested by me from now.
Hope devs will join so app status on flathub will be verified.

**Comment by flexxxxer** [comment]
For all who follows the issue: GPG/PGP signing works fine for me while running SourceGit in Flatpak locally. Commits, pushes, cloning repos, etc - work fine. Today or tomorrow submission request to Flathub will be created. But package status not yet known.

@love-linger I would like to ask about you joining to Flathub submission discussion soon so app package status will be "verified" with you being added to package maintainers/contributors (I hope me too so I can assist and help somewhat). Can you?
